### ISSUE TITLE
博主，请教一个问题

### ISSUE THREAD

**Issue by AlmostSir777** [xindizhiyin2014/JKWKWebViewHandler#2]
类似这种的wk应该怎么监测js的window.nativeFunction.showNavigationBar('0')，获取到H5 showXX 方法传给我的值呢？中间他们定义了一个nativeFunction的类去管理这些方法，webview使用jscontext网上有方法实现了，现在想用wk，就不知道怎么处理了

**Comment by xindizhiyin2014** [comment]
双方约定一个js方式，然后传递参数比如0，1来决定native是否显示和隐藏navigationBar
